# Some basic programming exercises on numpy

In [216]:
import numpy as np

#### 1. Create a vector 'int_vector' (1 dimensional array) filled with random 10 integer numbers

In [217]:
# code

int_vector = np.random.randint(10,50,10)  # returns 10 random integers between 10 and 50
print(int_vector)

[40 49 49 34 23 15 15 25 32 23]


#### 2. Create a vector 'rand_vector' filled with random 10 numbers between 0 and 1

In [218]:
# code
rand_vector = np.random.rand((10))
print(rand_vector)

[ 0.47414359  0.86603897  0.82003187  0.21010613  0.69947845  0.44772293
  0.57594929  0.03251073  0.05849033  0.96966096]


#### 3. Find the smallest and largest element in int_vector you created in step 1. 
 * Do this with and without using the numpy in-built function. Print the result
 

In [219]:
# code

def max_min(data):
    ''' 
    Find maximum and minimum element in a vector 
    Here we do not use any in-built function
    '''
    
    large=small=data[0]   # take first element as reference
    for i in range(1, len(data)):
        if data[i] > large:
            large=data[i]
        if data[i] < small:
            small=data[i]
        
    return large, small   
    
    
def max_min2(data):
    return np.max(data), np.min(data)

In [220]:
# call max_min passing int_vector

max_min(int_vector)

(49, 15)

In [221]:
max_min2(int_vector)

(49, 15)

#### 4. Create a vector 'vect1' with 9 elements equally spaced between 10 and 100  

In [222]:
# code

vect1 = np.linspace(10,100,9)
print(vect1)

[  10.     21.25   32.5    43.75   55.     66.25   77.5    88.75  100.  ]


#### 5. Create a 4x4 matrix 'mat1' that has 1 in its diagonal entry and 0 else where.

In [223]:
mat1 = np.diag((1,1,1,1))   # we specify diagonal elements to be integers 1's
print(mat1)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [224]:
# Alternatively, we could also do it this way
mat1a = np.eye(4)
print(mat1a)         # but note the difference. Here default data type for elements of numpy array is float

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


#### 6. Create a 5x5 matrix 'mat2' that is populated with random numbers between 0 and 1

In [225]:
mat2 = np.random.rand(5,5)
print(mat2)

[[ 0.48103197  0.22182563  0.74546855  0.93083756  0.32842686]
 [ 0.89460818  0.57990108  0.4483588   0.61617846  0.98186547]
 [ 0.60220148  0.7610408   0.81480776  0.53502852  0.95026389]
 [ 0.42587319  0.19827935  0.01188177  0.101885    0.35728372]
 [ 0.06889465  0.0827122   0.13790144  0.12581059  0.62833723]]


#### 7. Save the contents of 'mat2' to a csv file called 'mat2.csv'. 
 * Make sure you preserve 6 values after the decimal point.
 * Next read the contents of the csv file 'mat2.csv' and print its contents on screen

In [226]:
# save with 6 point precision 

np.savetxt('mat2.csv', mat2, delimiter=',', fmt='%.6f')

In [227]:
# read the contents of csv into mat2_data 

mat2_data = np.genfromtxt('mat2.csv', delimiter=',')

In [228]:
# print the contents. Each item has only 6 values after the decimal point

print(mat2_data)

[[ 0.481032  0.221826  0.745469  0.930838  0.328427]
 [ 0.894608  0.579901  0.448359  0.616178  0.981865]
 [ 0.602201  0.761041  0.814808  0.535029  0.950264]
 [ 0.425873  0.198279  0.011882  0.101885  0.357284]
 [ 0.068895  0.082712  0.137901  0.125811  0.628337]]


#### 8. Define a function 'operation' that takes three input arguments: data1, data2 and operationType
 * Data1 and data2 can be a scalar, vector or matrix.
 * operationType is a string variable that takes one of the following 4 values and performs element-wise operation for
   * add, subtract, multiply, divide
 * The function must return the result of the operation to the caller
   


In [229]:
def operation(data1,data2,operationType):
    
    if operationType == 'add':
        result = data1 + data2
    elif operationType == 'subtract':
        result = data1 - data2
    elif operationType == 'multiply':
        result = data1 * data2
    elif operationType == 'divide':
        result == data1 / data2
    return result
        

#### 9. Test the function 'operation' for different operations (say, add, multiply) on following inputs 
 * a)  A 4 element random vector 'rand_v' and the matrix mat1 that was created earlier. Function call will be: operation(rand_v, mat1, 'add') and operation(rand_v, mat1, 'multiply').
 * b) When you call the function as: operation(mat1, mat2, 'add'), where mat1 and mat2 are matrices created earlier. What output do you get ? 
 
 Observe the results obtained. Illustration of broadcasting. 

In [230]:
# code for a)

# testing add
rand_v = np.random.randint(1,50,4)   # get me 4 random integers between 1 and 50
result = operation(rand_v, mat1, 'add')

print(rand_v)
print(mat1)

print(result)    # 1d vector is broadcasted to match dimension of the 4x4 matrix before performing computation !

[23 10 10 47]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[24 10 10 47]
 [23 11 10 47]
 [23 10 11 47]
 [23 10 10 48]]


In [231]:
# testing for multiplication

result1 = operation(rand_v, mat1, 'multiply')
print(result1)

[[23  0  0  0]
 [ 0 10  0  0]
 [ 0  0 10  0]
 [ 0  0  0 47]]


In [232]:
# code for b)

#result2 = operation(mat1, mat2, 'add')

# This would not be possible. 
# It wil throw error message as Broadcasting is simply not possible here. We cannot create 5x5 replicating copies of 
# 4x4 matrix.

#### 10. Create a numpy vector comprising of 25 elements randomly drawn from a standard normal distribution. 
 * Next, convert this to a two dimensional 5 x 5 matrix called 'mat5x5' and print the matrix. 


In [233]:
mat5x5 =np.random.standard_normal(25).reshape(5,5)
print(mat5x5)

[[ 0.812077   -0.18963545 -1.25980741 -0.33343571 -0.42082913]
 [-0.60640854  2.0612364   1.5505929  -0.74859293 -0.34109574]
 [ 0.03698599  0.36081071  0.94343503  1.25633304  0.20267221]
 [-0.08813358  0.19700717  0.42355587 -0.95282093 -0.31280008]
 [-0.23649389 -0.31821087 -1.14750364  0.73017084 -1.25845445]]


In [234]:
print(mat5x5.shape)

(5, 5)


#### 11. Save the three matrices mat1, mat2 and mat5x5 as a compressed numpy binary file 'compressed_matrix'
 * Next also read the file 'compressed_matrix' to access individual matrix and print them.
 

In [235]:
# save matrices in compressed form

np.savez('compressed_matrix', mat1=mat1, mat2=mat2, mat5x5=mat5x5)

In [236]:
# read and print the compressed matrix

the_compressed_data = np.load('compressed_matrix.npz')

print(the_compressed_data.files)    # to view the file names in zipped data

['mat1', 'mat2', 'mat5x5']


In [237]:
# For example, lets just access the last file and print it 
print(the_compressed_data['mat5x5'])

[[ 0.812077   -0.18963545 -1.25980741 -0.33343571 -0.42082913]
 [-0.60640854  2.0612364   1.5505929  -0.74859293 -0.34109574]
 [ 0.03698599  0.36081071  0.94343503  1.25633304  0.20267221]
 [-0.08813358  0.19700717  0.42355587 -0.95282093 -0.31280008]
 [-0.23649389 -0.31821087 -1.14750364  0.73017084 -1.25845445]]


In [238]:
for file in the_compressed_data.files:    # You can print all the files in this way.
    print(the_compressed_data[file])      # not a good idea if your files are large

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[ 0.48103197  0.22182563  0.74546855  0.93083756  0.32842686]
 [ 0.89460818  0.57990108  0.4483588   0.61617846  0.98186547]
 [ 0.60220148  0.7610408   0.81480776  0.53502852  0.95026389]
 [ 0.42587319  0.19827935  0.01188177  0.101885    0.35728372]
 [ 0.06889465  0.0827122   0.13790144  0.12581059  0.62833723]]
[[ 0.812077   -0.18963545 -1.25980741 -0.33343571 -0.42082913]
 [-0.60640854  2.0612364   1.5505929  -0.74859293 -0.34109574]
 [ 0.03698599  0.36081071  0.94343503  1.25633304  0.20267221]
 [-0.08813358  0.19700717  0.42355587 -0.95282093 -0.31280008]
 [-0.23649389 -0.31821087 -1.14750364  0.73017084 -1.25845445]]


#### 11. Compute the following statistics for the matrix mat5x5
 * a) Global mean and mean across each dimension
 * b) Global variance and variance across each dimension
 

In [239]:
# code for a)
global_mean = np.mean(mat5x5)
print('Global mean : ', global_mean)

dimension_mean = np.mean(mat5x5, axis=0)
print('Mean across each dimension\n ', dimension_mean)


Global mean :  0.0144261920404
Mean across each dimension
  [-0.0163946   0.42224159  0.10205455 -0.00966914 -0.42610144]


In [240]:
# code for b)

global_var = np.var(mat5x5)
print('Global variance : ', global_var)

dimension_var = np.var(mat5x5, axis=0)
print('Variance across each dimension\n ', dimension_var)

Global variance :  0.709067694435
Variance across each dimension
  [ 0.21818426  0.73269433  1.26512225  0.73809864  0.22165176]


#### 12. Matrix multiplication 

In order to multiply two matrices, A and B, the number of columns in A must equal the number of rows in B. Thus, if A is an m x n matrix and B is an r x s matrix, n = r.

 * Given A = 3x3 and B = 3x4 matrices both filled with random numbers. 
 * Write a function 'matrix_multiply' that takes A and B as input and perform multiplication without using numpy in-built function 'dot'. Print the result.
 * Test whether your matrix multiplication code worked correctly by comparing the output you get using the inbuilt np.dot() function.
 
#### Hint: 
You will need to use two for loops. First loop controls the row dimension and the innermost control how many items need to be traversed in each row. 


In [241]:
# Code for the function

A = np.random.randint(1,100,9).reshape(3,3)     # lets take 9 random integer numbers from 1-100 
print(A.shape)

B = np.random.randint(1,100,12).reshape(3,4)    # 12 random integers and reshape into 3x4 matrix
print(B.shape)

(3, 3)
(3, 4)


In [242]:
# Lets print the contents of matrix A

print('Matrix A contents \n\n', A)

Matrix A contents 

 [[64 87 42]
 [ 2 31 99]
 [ 6 63 97]]


In [243]:
# Lets print the contents of matrix B

print('Matrix B contents \n\n', B)

Matrix B contents 

 [[61 59 55 33]
 [70 91 25 69]
 [97 94 71 67]]


In [244]:
def matrix_multiply(A,B):
    '''Performs multiplication of two matrices A and B and returns the product '''
    
    r1,c1 = A.shape    # get the rows and columns of matrix A
    r2,c2 = B.shape    # get the rows and columns of matrix B                          
    
    C = np.zeros((r1,c2))  # The shape of final matrix is (r1,c2)
    
    if c1 != r2 :
        print('The columns of matrix A do not match with rows of B. Multiplication not possible !!')
        return
    else:
        for i in range(0, r1):      # The result matrix rows = r1
            for j in range(0, c2):  # columns = c2
                
                for k in range(0, r2):        # loop along each elements in column j             
                    C[i,j] += A[i,k] * B[k,j]
                    
        return C

In [245]:
# Call the function passing the two matrices A and B

prod = matrix_multiply(A,B)
print(prod)

[[ 14068.  15641.   8677.  10929.]
 [ 11895.  12245.   7914.   8838.]
 [ 14185.  15205.   8792.  11044.]]


In [246]:
# check whether your code worked properly or not using np.dot() function

prod1 = np.dot(A,B)
print(prod1)

[[14068 15641  8677 10929]
 [11895 12245  7914  8838]
 [14185 15205  8792 11044]]


### Seems that the function is working fine !!